apiVersion: v1
kind: Service
metadata:
  name: devsecops-frontend
spec:
  type: NodePort
  selector:
    app: devsecops-frontend
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30081
      protocol: TCP